name: spotify
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Librería para realizar solicitudes HTTP
  flutter_dotenv: ^5.1.0
  http: ^1.2.1
  dio: ^5.4.0

  # Audio player compatible con Web, Android, iOS y más
  just_audio: ^0.10.5
  just_audio_web: ^0.4.16

  provider: ^6.1.1

  connectivity_plus: ^5.0.1
  cached_network_image: ^3.3.0

  permission_handler: ^11.0.0
  device_info_plus: ^9.0.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/canciones.json